format = """
[𜶉𜴟█](#fcf00a)\
$os\
$username\
[](bg:#0a242b fg:#fcf00a)\
$directory\
[](fg:#0a242b bg:#1c3a44)\
$git_branch\
$git_status\
[](fg:#1c3a44 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[█🬥🬖🬖](fg:#1d2230)\
\n$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[𜵔𜷙](bold fg:#fcf00a)[❯](bold bg:#fcf00a fg:#151b44)[🭝🭘](bold fg:#fcf00a)"
error_symbol = "[𜵔𜷙](bold fg:red)[✗](bold bg:red fg:#151b44)[🭝🭘](bold fg:red)"

[username]
show_always = true
style_user = "bg:#fcf00a fg:#151b44"
style_root = "bold bg:#fcf00a fg:#b8005a"
format = '[$user ]($style)'
disabled = false
aliases = { "root" = "root " }

[os]
style = "bg:#fcf00a fg:#151b44"
disabled = false

[os.symbols]
Arch = " "

[directory]
style = "bg:#0a242b fg:#F63369"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󱧶 "
"Projects" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Documentos" = "󱧶 "
"Descargas" = " "
"Música" = " "
"Imágenes" = " "

[git_branch]
symbol = ""
style = "bg:#1c3a44"
format = '[[ $symbol $branch ](fg:#2f96a4 bg:#1c3a44)]($style)'

[git_status]
style = "bg:#1c3a44"
format = '[[($all_status$ahead_behind )](fg:#2f96a4 bg:#1c3a44)]($style)'

[nodejs]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[   $time ](fg:#F14D41 bg:#1d2230)]($style)'
