# --------------------------------------------------------
# ░█░█░█░█░█▀█░█▀▄░█░░░█▀█░█▀█░█▀▄░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀░█░█░█▀▄░█▀█░▀█▀░▀█▀░█▀█░█▀█
# ░█▀█░░█░░█▀▀░█▀▄░█░░░█▀█░█░█░█░█░░░█░░░█░█░█░█░█▀▀░░█░░█░█░█░█░█▀▄░█▀█░░█░░░█░░█░█░█░█
# ░▀░▀░░▀░░▀░░░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░▀░░▀░░▀▀▀░▀▀▀░▀░▀
# See https://wiki.hyprland.org/Configuring/Keywords/
# --------------------------------------------------------

# V A R I A B L E S
source = modules/variables.conf

# E N V I R O N M E N T   V A R I A B L E S
# If the environment variables are managed by uwsm, you can find them 
# in the "env" and "env-hyprland" files inside the "~/.config/uwsm/" directory,
# and you can comment the source line below.
# source = modules/env-variables.conf

# M O N I T O R S
source = modules/monitors.conf

# A U T O   S T A R T
source = modules/autostart.conf

# A P P E A R A N C E
source = modules/appearance.conf

# A N I M A T I O N S
source = modules/animations.conf

# L A Y O U T
source = modules/layout.conf

# M I S C   S E T T I N G S
source = modules/misc.conf

# I N P U T   D E V I C E S
# (keyboard, touchpad and other devices)
source = modules/input.conf

# K E Y B I N D I N G S
source = modules/keybindings.conf

# W I N D O W S   R U L E S
source = modules/window-rules.conf

# P E R M I S S I O N S
source = modules/permissions.conf
