# --------------------------------------------------------
# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▀█░█▀█░█▀▄
# ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█▀█░█░█░█░█
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀░▀░▀▀░
# ░█░█░█▀█░█▀▄░█░█░█▀▀░█▀█░█▀█░█▀▀░█▀▀░░░█▀▄░█░█░█░░░█▀▀░█▀▀
# ░█▄█░█░█░█▀▄░█▀▄░▀▀█░█▀▀░█▀█░█░░░█▀▀░░░█▀▄░█░█░█░░░█▀▀░▀▀█
# ░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# --------------------------------------------------------

# G E N E R A L   R U L E S
windowrule = match:class .*, center on
windowrule = match:float on, min_size 200 100


# S P E C I F I C   R U L E S
windowrule = match:class ^(code)$, opacity 0.8 0.8
windowrule = match:class ^(mpv)$, float on
windowrule = match:class org.gnome.Loupe, float on
windowrule = match:class waypaper, float on, size (monitor_w*0.55) (monitor_h*0.7)

windowrule {
  name = customizer_apps
  match:class = ^(nwg-look|qt[56]ct|kvantummanager)$
  float = on
  size = (monitor_w*0.5) (monitor_h*0.55)
}

windowrule {
  name = dolphin
  match:class = org.kde.dolphin
  float = on
  size = 1000 500
}

windowrule {
  name = kde_portal
  match:class = ^(org.freedesktop.impl.portal.desktop.kde)$
  float = on
  size = (monitor_w*.55) (monitor_h*.5)
  center = on
}

windowrule {
  name = picture_in_picture
  match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
  float = on
  move = (monitor_w*.73) (monitor_h*.72)
  size = (monitor_w*.3) (monitor_h*.3)
}


# L A Y E R   R U L E S
layerrule {
  name = rofi_layer
  match:namespace = rofi
  blur = on
  ignore_alpha = 0
  animation = slide left
}

layerrule {
  name = wlogout_layer
  match:namespace = logout_dialog
  blur = off
  # animation = popin
  animation = fadeLayers
}

layerrule {
  name = notification_layer
  match:namespace = notifications
  blur = on
  # ignore_alpha = 0
  animation = slide right
}

