# --------------------------------------------------------
# ░█░░░█▀█░█▀█░█░█░░░█▀█░█▀█░█▀▄░░░█▀▀░█▀▀░█▀▀░█░░
# ░█░░░█░█░█░█░█▀▄░░░█▀█░█░█░█░█░░░█▀▀░█▀▀░█▀▀░█░░
# ░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░▀░▀░▀░▀░▀▀░░░░▀░░░▀▀▀░▀▀▀░▀▀▀
# Refer to https://wiki.hyprland.org/Configuring/Variables/
# --------------------------------------------------------

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
  gaps_in = 6
  gaps_out = 13

  border_size = 2

  # https://wiki.hyprland.org/Configuring/Variables/#variable-types 
  # for info about colors
  # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  col.active_border = rgb(E82750) rgb(6A0B20) rgb(E82750) 30deg
  # col.active_border = rgb(FF0055) rgb(C80044) rgb(780022) 30deg
  # col.active_border = rgb(FF0055) rgb(E82B52) 30deg
  # col.active_border = rgb(F861FF) rgb(7F5EDF) rgb(1FCDE7) 30deg
  # col.active_border = rgb(C4FF3C) rgb(5E8D14) rgb(A6F900) 30deg


  # col.inactive_border = rgba(595959aa)
  col.inactive_border = rgba(00000000)

  # Set to true enable resizing windows by clicking and dragging on 
  # borders and gaps
  resize_on_border = true 

  # Please see https://wiki.hyprland.org/Configuring/Tearing/ 
  # before you turn this on
  allow_tearing = false

  layout = dwindle
  # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
  rounding = 10
  # 2 = circle, higher = squircle, 4 = very obvious squircle
  rounding_power = 2.4

  # Change transparency of focused and unfocused windows
  active_opacity = 1.0
  inactive_opacity = 1.0

  # https://wiki.hyprland.org/Configuring/Variables/#shadow
  shadow {
    enabled = false
    range = 4
    render_power = 3
    color = rgba(1a1a1aee)
    color_inactive = rgba(00000000)
  }

  # https://wiki.hyprland.org/Configuring/Variables/#blur
  # blur {
  #   enabled = true
  #   new_optimizations = true
  #   size = 3
  #   passes = 1
  #   vibrancy = 0.1696
  #   noise = 0.0117
  #   popups = true
  #   ignore_opacity = true
  # }
  blur {
      enabled = true
      new_optimizations = true
      size = 10 #10
      passes = 4 #4
      brightness = 1
      noise = 0.0117
      contrast = 0.89
      vibrancy = 0.5
      vibrancy_darkness = 0.5
      popups = false
      popups_ignorealpha = 0.6
      input_methods = true
      input_methods_ignorealpha = 0.8
  }
}


