# --------------------------------------------------------
# ░█▀█░█░█░▀█▀░█▀█░█▀▀░▀█▀░█▀█░█▀▄░▀█▀
# ░█▀█░█░█░░█░░█░█░▀▀█░░█░░█▀█░█▀▄░░█░
# ░▀░▀░▀▀▀░░▀░░▀▀▀░▀▀▀░░▀░░▀░▀░▀░▀░░▀░
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
# --------------------------------------------------------

exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- ~/.local/bin/battery-level
# exec-once = uwsm app -- easyeffects --gapplication-service
exec-once = ~/.local/bin/bluetooth-startup
exec-once = dunst &
